### ISSUE TITLE
No categories on new install

### ISSUE THREAD

**Issue by kriszentner** [OfficeDev/microsoft-teams-apps-greatideas#12]
Hi folks,

After going through the entire deployment, I seem to be successful except there are no categories, and I don't see any instructions on managing categories after the initial install. Much of the functionality is disabled without the ability to select at least one category. I can probably insert some into the Azure Table manually, but that doesn't seem to be the right way to do things. 

I see there's a nifty "Manage Categories" button on the "Ideas" tab of the sample "Northwind Traders" tab:
![image](https://user-images.githubusercontent.com/4173978/91236698-8a4a8a80-e6ed-11ea-8f5e-971aeb56d568.png)

Though to add either the Great Ideas app or Great Ideas Curator app into a tab requires at least one category. Some clarity on how to do this would be appreciated.

**Comment by BraunJonathan** [comment]
Did you find a solution on this one?
I've got the same issue...

**Comment by kriszentner** [comment]
Not yet!

**Comment by BraunJonathan** [comment]
I managed to see the Add new category button by adding the curator app into a team (as a new tab) but i ran ino a 403 error when trying to save the new category...

**Comment by nisgi** [comment]
I am facing , same issue with authentication issue.

In code, below authentication method is causing issue as per logs in application insights.
ValidIssuers = AuthenticationServiceCollectionExtensions.GetValidIssuers(configuration),


from Arm template "https://login.microsoftonline.com/TENANT_ID/v2.0,https://sts.windows.net/TENANT_ID/"
The keys are not matching from both this issuers.

**Comment by nisgi** [comment]
I am facing , same issue with authentication issue.

In code, below authentication method is causing issue as per logs in application insights.
ValidIssuers = AuthenticationServiceCollectionExtensions.GetValidIssuers(configuration),


from Arm template "https://login.microsoftonline.com/TENANT_ID/v2.0,https://sts.windows.net/TENANT_ID/"
The keys are not matching from both this issuers.
