### ISSUE TITLE
Enhancement requests

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-greatideas#27]
Dear team,

I have installed the Great Ideas app (from latest #24 that was merge back into Master branch on Jan 11) and demonstrate it to my team members in my organization. There are some feed backs after the demo on how this app can be improved. So below are the list of feature requests that we would like to see on the app.

The most important feature as a minimum viable product that should be added in next release are:
1. Ability for the Curator/admin to edit or delete an existing idea once it has been approved or rejected. I am not sure if others can edit submitted ideas, but at this moment other than manage categories feature, there is no edit or delete button on an existing idea record for Curator

![image](https://user-images.githubusercontent.com/71060262/105128869-decc2780-5b1e-11eb-93fe-7bfbbc4abb01.png)

It would be good to able to manage submitted ideas. When an existing submitted idea record can be updated, we like to have the following field be edited:
* Description - Ability to edit it.
* Tag - Ability to remove existing tag or add a new tag
* Status field - Ability to edit the status (for curator/admin) to implemented, archived.
* Supporting document - Ability to update the link
* Category - Ability to change the category value from drop down value

The other minor (nice to have) enhancement requests are:
2. Ability to merge multiple ideas

Thank you for your considerations. Please let me know if the above feature enhancements is in the road map app for further improvements/fixes.

Kind regards
David

**Comment by v-smahaj** [comment]
Thanks for the feedback!
For this repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
