### ISSUE TITLE
Manifest image not showing in Deployment guide

### ISSUE THREAD

**Issue by Snowfox05** [OfficeDev/microsoft-teams-apps-greatideas#5]
Manifest image referenced in deployment guide is not showing so instructions are unclear as to how to update the manifest.json to suit Teams app deployment.
Thanks

**Comment by abbodh** [comment]
Hi @Snowfox05 - can you please let us know the image you are referring, as [Step 3](https://github.com/OfficeDev/microsoft-teams-apps-greatideas/wiki/Deployment-guide#step-3-create-the-teams-app-packages) covers what needs to be updated in manifest. 

Kindly let us know if there is anything missing.

**Comment by abbodh** [comment]
Hi @Snowfox05 - the deployment guide is further revised for better understanding. Please take a look and feel free to open an issue if you see anything confusing.
