### ISSUE TITLE
Deployment Fails - Source Control

### ISSUE THREAD

**Issue by lkisweeney** [OfficeDev/microsoft-teams-apps-greatideas#9]
Hi The Template is failing 

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}

Microsoft.Web/sites/sourcecontrols

Deployment Correlation ID
eecbd6b5-a804-4a37-86ba-97d7cdab9505

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}

The app and resource group has a unique name.

Where could the conflict be?

**Comment by abbodh** [comment]
It seems there is an issue with dependent package of app insights - https://github.com/microsoft/ApplicationInsights-JS/issues/1293 

We are working on updating the version to resolve build failure.

**Comment by abbodh** [comment]
#10 has the fix available. This is under review and should be available soon in master branch.

**Comment by lkisweeney** [comment]
Thanks @abbodh - Is the master branch likely to be updated this week?

**Comment by abbodh** [comment]
@lkisweeney it's merged to master today.

Tip: If you have the instance still up, please just 'Sync' the app service instead of doing end to end deployment again.

**Comment by lkisweeney** [comment]
Thanks - all deployed and working.

**Comment by lkisweeney** [comment]
@abbodh - is there a way the moderator can update the user's idea with current status...or would we need to add this ourselves?
